title: Utalp
name: Utalp
email: admin@utalp.com
description: Revolution Never Ends

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text


parallax_image_one: assets/images/utalp.com main1.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/utalp.com blog.jpg

project_one: Flamingo Coasters
project_one_description: Describe your project!
project_one_url: https://www.amazon.com/Utalp-Pier-Wood-Flamingo-Coasters/dp/B07H4T9189/ref=sr_1_2?ie=UTF8
project_one_icon: location_on

project_two: Ice Cream Coasters
project_two_description: Describe your project!
project_two_url: https://www.amazon.com/Utalp-Pier-Wood-Cream-Coasters/dp/B07H4WFBGS/ref=sr_1_1?ie=UTF8
project_two_icon: photo_camera


project_three: Forest Grocary Bag
project_three_description: Describe your project!
project_three_url: https://www.amazon.com/dp/B07FTWNC9T/ref=twister_B07FTR72T5?_encoding=UTF8
project_three_icon: hotel

project_two: Flowers Grocery Bag
project_two_description: Describe your project!
project_two_url: https://www.amazon.com/dp/B07FTQJJXD/ref=twister_B07FTR72T5?_encoding=UTF8
project_two_icon: photo_camera


portfolio_heading: Products
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: android
 
icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Details

twitter: https://twitter.com
instagram: https://instagram.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: https:/utalp.com/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: UA-125962995-1

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
